import Link from '@/components/marketing/smart-link';
import { FadeUp } from './fade-up';
import { EN_COPY, type HomepageCopy } from '@/lib/i18n/homepage-copy';

// Real worked examples — each generated by the same composePlan() that
// powers the wizard (same trade-defence data, preferential-origin
// pathways and compliance overlay). Hrefs are EN-canonical; the example
// pages are themselves locale-aware.
const EXAMPLE_HREFS = [
  '/examples/chinese-ebike-importer-87pct-combined-ad-cvd/',
  '/examples/cn-aluminium-cbam-plus-32pct-ad/',
  '/examples/vietnam-electronics-evfta-zero-duty/',
];

export function WorkedExamples({
  copy = EN_COPY.examplesSection,
}: {
  copy?: HomepageCopy['examplesSection'];
}) {
  return (
    <section id="examples" className="bg-[var(--color-ink)] py-20 md:py-24">
      <div className="mx-auto max-w-[1080px] px-6">
        <FadeUp className="mb-12 text-center">
          <h2 className="mx-auto max-w-[24ch] text-[clamp(2rem,4vw,3rem)] leading-[1.1]">{copy.title}</h2>
          <Link href="/examples/" className="link-arrow mt-4">
            {copy.viewAll} <span aria-hidden>›</span>
          </Link>
        </FadeUp>

        <div className="grid grid-cols-1 gap-5 md:grid-cols-3">
          {copy.items.map((ex, i) => (
            <Link
              key={EXAMPLE_HREFS[i]}
              href={EXAMPLE_HREFS[i]}
              className="tile group flex flex-col gap-5 p-8 transition-transform duration-300 hover:scale-[1.015]"
            >
              <div className="flex items-center justify-between text-[12px] text-[var(--color-ivory-mute)]">
                <span>{ex.tag}</span>
                <span>{ex.lane}</span>
              </div>
              <div>
                <div className="text-[clamp(3rem,5vw,4rem)] font-semibold leading-none tracking-[-0.04em] text-[var(--color-ivory)]">
                  {ex.headline}
                </div>
                <div className="mt-2 text-[14px] text-[var(--color-ivory-mute)]">{ex.headlineCaption}</div>
              </div>
              <p className="text-[15px] leading-[1.55] text-[var(--color-ivory-dim)]">{ex.summary}</p>
              <span className="mt-auto text-[15px] text-[var(--color-link)] group-hover:underline">
                {copy.readBreakdown} ›
              </span>
            </Link>
          ))}
        </div>
      </div>
    </section>
  );
}
