'use client';

import Link from 'next/link';
import { useState } from 'react';
import { FadeUp } from './fade-up';
import { EN_COPY, type HomepageCopy } from '@/lib/i18n/homepage-copy';

// Real worked examples from the live OrcaTrade.pl site. Each one is a
// scenario generated by the same composePlan() function that powers the
// wizard — same trade-defence database, same preferential-origin
// pathways, same compliance overlay. Hrefs are EN-canonical; the example
// detail pages are themselves locale-aware.
const EXAMPLE_HREFS = [
  '/examples/chinese-ebike-importer-87pct-combined-ad-cvd/',
  '/examples/cn-aluminium-cbam-plus-32pct-ad/',
  '/examples/vietnam-electronics-evfta-zero-duty/',
];

type ExampleItem = HomepageCopy['examplesSection']['items'][number] & { href: string };

function ExampleCard({ ex, readBreakdown }: { ex: ExampleItem; readBreakdown: string }) {
  const [spot, setSpot] = useState({ x: 0, y: 0, visible: false });

  return (
    <Link
      href={ex.href}
      onMouseMove={(e) => {
        const rect = e.currentTarget.getBoundingClientRect();
        setSpot({
          x: e.clientX - rect.left,
          y: e.clientY - rect.top,
          visible: true,
        });
      }}
      onMouseLeave={() => setSpot((p) => ({ ...p, visible: false }))}
      className="group relative isolate flex flex-col gap-6 overflow-hidden bg-[var(--color-ink)] p-9 transition-colors duration-700 hover:bg-[var(--color-navy-soft)] md:p-10"
    >
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0 z-[1] transition-opacity duration-700 ease-out"
        style={{
          opacity: spot.visible ? 1 : 0,
          background: `radial-gradient(340px circle at ${spot.x}px ${spot.y}px, rgba(250, 250, 247, 0.055), transparent 72%)`,
        }}
      />

      <div className="relative z-[2] flex items-center justify-between">
        <span className="font-serif text-[12px] italic text-[var(--color-ivory-mute)]">
          {ex.tag}
        </span>
        <span className="text-[10.5px] font-medium tracking-tight text-[var(--color-ivory-dim)]">
          {ex.lane}
        </span>
      </div>

      <div className="relative z-[2] flex flex-col gap-2">
        <div
          className="font-serif text-[clamp(3.4rem,5.4vw,4.6rem)] leading-[0.95] tracking-[-0.028em] text-[var(--color-ivory)]"
          style={{ fontVariationSettings: "'SOFT' 30, 'opsz' 144", fontWeight: 550 }}
        >
          {ex.headline}
        </div>
        <div className="font-serif text-[13px] italic text-[var(--color-ivory-dim)]">
          {ex.headlineCaption}
        </div>
      </div>

      <p className="relative z-[2] mt-auto max-w-[38ch] text-[14.5px] leading-[1.6] text-[var(--color-ivory-dim)]">
        {ex.summary}
      </p>

      <span className="relative z-[2] inline-flex items-center gap-2 text-[12.5px] font-medium text-[var(--color-ivory)]">
        <span className="relative">
          {readBreakdown}
          <span className="absolute -bottom-0.5 left-0 h-px w-0 bg-[var(--color-ivory)]/70 transition-[width] duration-500 ease-[cubic-bezier(0.16,1,0.3,1)] group-hover:w-full" />
        </span>
        <span
          aria-hidden
          className="transition-transform duration-500 group-hover:translate-x-0.5"
        >
          →
        </span>
      </span>
    </Link>
  );
}

export function WorkedExamples({
  copy = EN_COPY.examplesSection,
}: {
  copy?: HomepageCopy['examplesSection'];
}) {
  const examples: ExampleItem[] = copy.items.map((item, i) => ({ ...item, href: EXAMPLE_HREFS[i] }));
  return (
    <section
      id="examples"
      className="border-b border-[var(--color-navy-line)] bg-[var(--color-ink)] py-20 md:py-32"
    >
      <div className="mx-auto max-w-[1280px] px-6">
        <FadeUp className="mb-14 flex flex-col items-start justify-between gap-6 md:flex-row md:items-end">
          <h2
            className="max-w-[28ch] font-serif text-[clamp(2.2rem,3.8vw+0.4rem,3.4rem)] leading-[1.08] tracking-[-0.022em] text-[var(--color-ivory)]"
            style={{ fontVariationSettings: "'SOFT' 35, 'opsz' 144" }}
          >
            {copy.title}
          </h2>
          <Link
            href="/examples/"
            className="group inline-flex items-center gap-2 text-[12.5px] font-medium text-[var(--color-ivory)] transition-all duration-500"
          >
            <span className="relative">
              {copy.viewAll}
              <span className="absolute -bottom-0.5 left-0 h-px w-0 bg-[var(--color-ivory)]/70 transition-[width] duration-500 ease-[cubic-bezier(0.16,1,0.3,1)] group-hover:w-full" />
            </span>
            <span aria-hidden className="transition-transform duration-500 group-hover:translate-x-0.5">
              →
            </span>
          </Link>
        </FadeUp>

        <div className="grid grid-cols-1 gap-px border border-[var(--color-navy-line)] bg-[var(--color-navy-line)] md:grid-cols-3">
          {examples.map((ex) => (
            <ExampleCard key={ex.href} ex={ex} readBreakdown={copy.readBreakdown} />
          ))}
        </div>
      </div>
    </section>
  );
}
