import type { Metadata } from 'next';
import { EditorialHeader } from '@/components/marketing/editorial-header';
import { HubCard } from '@/components/marketing/hub-card';
import { FadeUp } from '@/components/marketing/fade-up';

export const metadata: Metadata = {
  title: 'Worked examples — OrcaTrade Group',
  description:
    'Eight real lane scenarios, each generated by the same composePlan() function that powers the wizard. Calculator-grounded, citation-checked.',
};

// Eight real worked examples on the live site. Each link resolves to a
// generated example page in the root project; they will continue to do
// so when this hub is deployed alongside the static guides.
const EXAMPLES = [
  {
    href: '/examples/chinese-ebike-importer-87pct-combined-ad-cvd/',
    kicker: 'Anti-dumping · CVD',
    title: '87% combined AD + CVD on Chinese e-bikes.',
    description:
      '€97,300 of duty per €100,000 shipment. AD 70.1% plus CVD 17.2% layered on top of 10% MFN.',
    detail: 'e-bikes · CN → PL',
  },
  {
    href: '/examples/bangladesh-apparel-eba-zero-duty/',
    kicker: 'Preferential origin',
    title: 'Zero EU duty under Everything But Arms.',
    description:
      '€6,000 saving per €50,000 apparel shipment with a valid REX statement. EBA continues until 2029 under the transitional period.',
    detail: 'apparel · BD → PL',
  },
  {
    href: '/examples/turkey-cold-rolled-steel-atr-with-ad/',
    kicker: 'A.TR · Anti-dumping',
    title: 'A.TR Customs Union does not waive 23.3% AD.',
    description:
      'The procurement misconception: "TR goods are duty-free under A.TR." True for MFN — but trade defence overrides preferential origin.',
    detail: 'steel · TR → DE',
  },
  {
    href: '/examples/vietnam-electronics-evfta-zero-duty/',
    kicker: 'EVFTA · compliance stack',
    title: 'EVFTA — zero duty plus RoHS/WEEE/CE compliance.',
    description:
      'Zero duty with a REX origin declaration. Chapter 85 triggers CE LVD/EMC/RED + RoHS + WEEE producer registration.',
    detail: 'electronics · VN → DE',
  },
  {
    href: '/examples/cn-aluminium-cbam-plus-32pct-ad/',
    kicker: 'CBAM · Anti-dumping',
    title: 'CBAM declarant status + 32% anti-dumping duty.',
    description:
      'Aluminium extrusions from China carry 32% AD on top of 6% MFN and CBAM declarant status from January 2026.',
    detail: 'aluminium · CN → DE',
  },
  {
    href: '/examples/cosmetics-india-reach-cosmetics-regulation/',
    kicker: 'Cosmetics Regulation 1223/2009',
    title: 'Responsible Person + CPNP notification before market.',
    description:
      'Cosmetics chapter 33 triggers Cosmetics Regulation 1223/2009. Compliance overlay alone delays first shipment 3–6 months.',
    detail: 'cosmetics · IN → DE',
  },
  {
    href: '/examples/polish-apparel-importer-from-china/',
    kicker: 'Apparel · classification',
    title: 'A Polish apparel importer routing from China.',
    description:
      'Woven versus knitted classification, REX-eligibility, and the trade-defence overlay on cotton fabrics from China.',
    detail: 'apparel · CN → PL',
  },
  {
    href: '/examples/south-korea-machinery-eukfta-zero-duty/',
    kicker: 'EU–Korea FTA',
    title: 'Zero duty under the EU–Korea FTA.',
    description:
      'Industrial machinery from South Korea under the EUKFTA. Origin declaration on the invoice and a clean lane through the EU.',
    detail: 'machinery · KR → DE',
  },
];

export default function ExamplesHubPage() {
  return (
    <>
      <EditorialHeader
        kicker="Worked examples"
        title={
          <>
            Eight real scenarios.
            <br className="hidden md:block" /> Calculator-grounded numbers.
          </>
        }
        lead="Each example below is generated from the same composePlan() function that powers the wizard — same trade-defence database, same preferential-origin pathways, same compliance overlay."
        meta="Click any card to see the full plan, or open it directly in the wizard."
      />

      <section className="bg-[var(--color-ink)] py-20 md:py-28">
        <div className="mx-auto max-w-[1280px] px-6">
          <FadeUp>
            <div className="grid grid-cols-1 gap-px border border-[var(--color-navy-line)] bg-[var(--color-navy-line)] md:grid-cols-2 lg:grid-cols-4 [&>*]:transition-opacity [&>*]:duration-700 [&:has(>*:hover)>*:not(:hover)]:opacity-45">
              {EXAMPLES.map((ex) => (
                <HubCard key={ex.href} {...ex} />
              ))}
            </div>
          </FadeUp>
        </div>
      </section>
    </>
  );
}
