#!/usr/bin/env node
'use strict';

// Generate docs/api/openapi.json from lib/contracts/v1/ + the endpoint
// metadata file.
//
// Phase 0 task P0.J of docs/execution-plan.md. See ADR 0014.
//
// Usage:
//   node scripts/generate-openapi.js              # write to docs/api/openapi.json
//   node scripts/generate-openapi.js --stdout     # write to stdout (for diff)
//
// The generator is deterministic — given the same inputs, byte-identical
// output. test/openapi-drift.test.js asserts the committed openapi.json
// is up to date by regenerating + diffing. CI catches a stale spec.

const fs = require('node:fs');
const path = require('node:path');

const { SCHEMAS } = require('../lib/contracts/v1');
const { ENDPOINTS } = require('../lib/contracts/v1/openapi-metadata');

const OPENAPI_VERSION = '3.1.0';
const API_VERSION = '1.0.0';
const OUT_PATH = path.resolve(__dirname, '..', 'docs', 'api', 'openapi.json');

/**
 * Convert OrcaTrade's tiny JSON-Schema-subset (per lib/contracts/v1/index.js)
 * to OpenAPI 3.1's JSON-Schema dialect.
 *
 * Differences:
 *   - `nullable: true` (our format / OpenAPI 3.0) → `type: [..., 'null']` (OpenAPI 3.1).
 *   - `type: ['boolean', 'object']` (multi-type) is already valid JSON Schema 2020-12.
 *
 * Recursively traverses properties + items. Pure function; no I/O.
 */
function toOpenApiSchema(schema) {
  if (schema === null || typeof schema !== 'object') return schema;
  if (Array.isArray(schema)) return schema.map(toOpenApiSchema);

  const out = {};
  for (const [key, value] of Object.entries(schema)) {
    if (key === 'nullable') continue; // handled separately below
    if (key === 'properties' && typeof value === 'object') {
      out.properties = {};
      for (const [propKey, propValue] of Object.entries(value)) {
        out.properties[propKey] = toOpenApiSchema(propValue);
      }
      continue;
    }
    if (key === 'items') {
      out.items = toOpenApiSchema(value);
      continue;
    }
    out[key] = value;
  }

  if (schema.nullable === true) {
    if (Array.isArray(out.type)) {
      if (!out.type.includes('null')) out.type = [...out.type, 'null'];
    } else if (out.type) {
      out.type = [out.type, 'null'];
    } else {
      out.type = 'null';
    }
  }

  return out;
}

/**
 * Build the full OpenAPI document from contracts + metadata.
 * Pure function. Returns a plain object ready for JSON.stringify.
 */
function buildOpenApiDoc() {
  const paths = {};

  for (const [name, endpoint] of Object.entries(ENDPOINTS)) {
    const schema = SCHEMAS[name];
    if (!schema) {
      throw new Error(`No SCHEMAS entry for endpoint "${name}" in lib/contracts/v1/index.js`);
    }

    const operation = {
      summary: endpoint.summary,
      description: endpoint.description,
      tags: endpoint.tags,
      operationId: name,
      responses: {
        '200': {
          description: 'Success.',
          content: {
            'application/json': {
              schema: toOpenApiSchema(schema),
            },
          },
        },
        '400': { description: 'Bad request — see body for details.' },
        '429': { description: 'Rate-limited.' },
        '500': { description: 'Internal error.' },
      },
    };

    if (endpoint.parameters) {
      operation.parameters = endpoint.parameters;
    }

    if (endpoint.requestBody) {
      operation.requestBody = {
        description: endpoint.requestBody.description,
        required: endpoint.requestBody.required,
        content: {
          'application/json': {
            schema: toOpenApiSchema(endpoint.requestBody.schema),
          },
        },
      };
    }

    if (!paths[endpoint.path]) paths[endpoint.path] = {};
    paths[endpoint.path][endpoint.method] = operation;
  }

  return {
    openapi: OPENAPI_VERSION,
    info: {
      title: 'OrcaTrade Public API',
      version: API_VERSION,
      description: [
        'The /api/v1/* public surface of OrcaTrade.',
        '',
        'Contracts are frozen per version (see ADR 0007 — Public API contracts under /api/vN/ are stable per version).',
        'Schemas pin required fields + their types but do NOT set additionalProperties:false — adding a new',
        'field is non-breaking; removing/renaming/retyping a pinned field is a breaking change that lands as a',
        'new version (/api/v2/, ADR 0007).',
        '',
        'This document is generated from lib/contracts/v1/ + lib/contracts/v1/openapi-metadata.js via',
        'scripts/generate-openapi.js. Drift between the source contracts and this artefact is enforced by',
        'test/openapi-drift.test.js. Do not edit this file by hand.',
      ].join('\n'),
      contact: {
        name: 'OrcaTrade',
        url: 'https://orcatrade.pl',
        email: 'security@orcatrade.pl',
      },
      license: {
        name: 'Proprietary',
      },
    },
    servers: [
      { url: 'https://orcatrade.pl', description: 'Production' },
    ],
    paths,
    components: {},
  };
}

function main() {
  const doc = buildOpenApiDoc();
  const serialised = JSON.stringify(doc, null, 2) + '\n';

  if (process.argv.includes('--stdout')) {
    process.stdout.write(serialised);
    return;
  }

  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, serialised);
  process.stdout.write(`Wrote ${OUT_PATH}\n`);
}

if (require.main === module) {
  main();
}

module.exports = { buildOpenApiDoc, toOpenApiSchema };
